### PR TITLE
Remove hardcoded SUSE theme and offline compression

### PR DESCRIPTION
**Pull request by toabctl**
Branding is the wrong place to do any changes like that.

### CODE REVIEW

**Comment by dirkmueller** [comment]
I'm not sure why we do pull requests against /SUSE-Cloud anway.. this is supposed to be rebased version of the /crowbar repo. 

I#m in favor of force-push removing the broken changes that got merged previously here.

**Comment by vuntz** [comment]
+1

**Comment by toabctl** [comment]
tbh I don't even know how https://build.suse.de/package/view_file/Devel:Cloud:6:Staging/crowbar-openstack/suse-branding.patch?expand=1 gets created from this branch...
@rsalevsky @tboerger can you help out here please?

**Comment by rsalevsky** [comment]
@toabctl `git format-patch --stdout upstream/master..suse-cloud/master-branding > /tmp/suse-branding.patch`

**Comment by vuntz** [comment]
@rsalevsky but that patch was not tracked in git before, iirc. When did that start, and was it announced? (I might have missed the announcement)

**Comment by rsalevsky** [comment]
@vuntz We missed that while we merged the crowbar repos, it was tracked before.

**Comment by toabctl** [comment]
@rsalevsky removed the commit (as suggested by @dirkmueller ). So this PR can be closed.

**Pull request closed without merging**
